name: github-actions
on: [push]
jobs:
  install-build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g aws-cdk
    - run: npm install
    - run: npm run install-lambda-modules
    - run: npm run build
    - run: npm run build-vue
    - run: cdk synth
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: cdk diff
    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@master
      env:
       DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
       PATHS: '/index.html'
       AWS_REGION: 'us-east-1'
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: cdk deploy --require-approval never